version: '3.4'
networks:
  dockerapi:
    driver: bridge

services:
  api:
    build: .
    ports:
      - "5000:80"
    depends_on: 
      - mypostgres
    environment:
      DB_CONNECTION_STRING: "Host=mypostgres;Port=5432;Database=mydb;Username=myuser;Password=mypassword"
    networks:
      - dockerapi

  mypostgres:
    image: "postgres"
    container_name: "mypostgres"
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "mydb"
    restart: always
    ports:
      - "54320:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - dockerapi

      
volumes:
  db_volume:
         