<<<<<<< HEAD
﻿version: '3.4'
networks:
  dockerapi:
    driver: bridge

=======
﻿version: '3'
>>>>>>> fdb2c5cd4e345a5d612aa4e857940f4dcce5e2d3
services:
  api:
    build: .
    ports:
<<<<<<< HEAD
      - "5000:80"
    depends_on: 
      - db
    networks:
      - dockerapi

  db:
    image: "postgres"
    container_name: "db"
    environment:
      - POSTGRES_USER=roy
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=mydb
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - dockerapi
=======
      - "5000:80"
>>>>>>> fdb2c5cd4e345a5d612aa4e857940f4dcce5e2d3
